== Metodología y organización: Kanban

Kanban es un método de gestión visual del trabajo originado en los sistemas de producción ajustada (_lean manufacturing_) de Toyota ---donde fue concebido como sistema de planificación _just-in-time_ dentro del Toyota Production System @hammarberg_kanban_2014[p.~49]--- y posteriormente adoptado de forma generalizada en el desarrollo de software. Su principio fundamental consiste en representar el estado de las tareas mediante un tablero dividido en columnas que reflejan las distintas fases del proceso productivo ---habitualmente "Por hacer", "En progreso" y "Hecho"---, con el objetivo de hacer visible el flujo de trabajo, limitar el trabajo en curso y facilitar la identificación de cuellos de botella, los tres principios básicos sobre los que se sustenta la metodología @hammarberg_kanban_2014[p.~49]. A diferencia de metodologías más prescriptivas como Scrum ---que organiza el desarrollo en iteraciones de duración fija con roles formales y ceremonias periódicas---, Kanban no prescribe roles, reuniones ni reglas concretas, sino que parte de la situación actual del equipo y le ayuda a identificar el siguiente paso para mejorarla @hammarberg_kanban_2014[p.~8]. Esta flexibilidad lo adapta con mayor naturalidad a contextos en los que el alcance del trabajo evoluciona de forma continua o en los que el equipo de desarrollo está integrado por una sola persona.

En el contexto de un trabajo de fin de máster de carácter unipersonal, la adopción íntegra de una metodología ágil de equipo resultaría artificial e innecesaria. Por ello, se ha optado por aplicar únicamente los elementos de Kanban que aportan valor real en este contexto: la visualización del trabajo pendiente mediante un tablero, la priorización explícita de las tareas y el registro del estado de avance ---dado que, como señalan #cite(<hammarberg_kanban_2014>, form: "prose"), Kanban permite mejorar significativamente sin imponer reglas o prácticas concretas @hammarberg_kanban_2014[p.~49]---. Se prescinde, en cambio, de los límites formales de trabajo en curso y de cualquier tipo de ceremonia periódica que no tenga sentido en un proyecto individual. Este enfoque pragmático permite mantener la trazabilidad del trabajo sin incurrir en la sobrecarga de proceso propia de metodologías diseñadas para equipos de mayor tamaño.

=== Herramienta de gestión: Backlog.md

Existen diversas herramientas ampliamente extendidas para la gestión visual de proyectos mediante tableros Kanban: Trello, Notion y Miro son algunas de las más habituales. Sin embargo, en este proyecto se ha optado por una aproximación diferente, motivada por el principio de "tareas como código": gestionar el trabajo pendiente mediante ficheros de texto plano versionados en el propio repositorio del proyecto, de la misma forma en que se versiona el código fuente.

La herramienta elegida para materializar este principio es Backlog.md, una utilidad de código abierto ---publicada bajo licencia MIT--- que convierte cualquier repositorio Git en un sistema de gestión de proyectos autocontenido. Su funcionamiento se basa en almacenar cada tarea como un fichero Markdown independiente dentro de un directorio `backlog/` en la raíz del repositorio. Cada fichero de tarea puede incluir una descripción detallada, criterios de aceptación, notas de implementación, dependencias respecto a otras tareas y el registro de decisiones tomadas durante su ejecución. Esta estructura favorece la trazabilidad completa del trabajo: el historial de Git refleja cuándo se creó cada tarea, cuándo se actualizó y cuándo se marcó como completada, sin necesidad de sistemas externos ni de sincronización con servicios en la nube.

Backlog.md ofrece dos interfaces de interacción sobre los mismos ficheros subyacentes: un tablero Kanban en terminal (`backlog board`) y una interfaz web con arrastrar y soltar (`backlog browser`), ambas con sincronización bidireccional en tiempo real con los ficheros Markdown. La @fig:backlog-browser y la @fig:backlog-terminal ilustran ambas vistas aplicadas al tablero real del proyecto, con las tareas distribuidas entre las columnas correspondientes a cada fase del desarrollo.

#figure(
  image("../../images/backlog-kanban-browser.png", width: 100%),
  caption: [Vista de la interfaz web de Backlog.md con las tareas del proyecto organizadas en columnas según su estado.],
) <fig:backlog-browser>

#figure(
  image("../../images/backlog-kanban-terminal.png", width: 100%),
  caption: [Vista del tablero Kanban en terminal de Backlog.md con las tareas del proyecto.],
) <fig:backlog-terminal>

Un aspecto especialmente relevante de Backlog.md en el contexto de este proyecto es su integración nativa con agentes de inteligencia artificial mediante el protocolo MCP (_Model Context Protocol_). Esta capacidad permite que herramientas como Claude Code operen directamente sobre las tareas del proyecto ---consultando su estado, creando nuevas entradas, actualizando el progreso o marcando criterios de aceptación como completados--- sin abandonar el entorno de desarrollo. La filosofía subyacente se denomina _spec-driven AI development_: cada tarea actúa como una especificación estructurada que guía el trabajo del agente de IA, con criterios de aceptación explícitos que delimitan el alcance y las condiciones de finalización de cada unidad de trabajo. Este modelo resulta especialmente adecuado para un proyecto en el que la asistencia de herramientas de inteligencia artificial se incorpora de forma sistemática al proceso de desarrollo.

El conjunto de estas características ---tareas como ficheros Markdown en el repositorio, versionado nativo con Git, interfaces múltiples sobre los mismos datos subyacentes, integración con agentes de IA y operación completamente local y privada--- convierte a Backlog.md en una solución coherente con los principios técnicos del proyecto y con el objetivo de mantener una trazabilidad completa del trabajo realizado a lo largo de todas las fases del TFM.
