== Prototipos de baja calidad (wireframes) <sec:wireframes>

El prototipado de baja calidad se llevó a cabo mediante un sistema propio de prototipado rápido, desarrollado específicamente para este proyecto en el directorio `apps/wireframe/`. En lugar de recurrir a herramientas de diseño visual convencionales como Figma o Sketch, se optó por construir una aplicación web de página única (_Single Page Application_) con React y TypeScript, apoyada en librerías de estilo _hand-drawn_ —en concreto, rough.js, wired-elements y rough-viz— que producen un acabado visual deliberadamente imperfecto. Este acabado comunica con claridad a cualquier observador la naturaleza no definitiva del prototipo, cumpliendo así la función semiótica esencial de un _wireframe_: distinguir la estructura conceptual de la apariencia final.

La elección de este enfoque sobre las herramientas de diseño habituales respondió a dos criterios complementarios. En primer lugar, la interactividad: los _wireframes_ resultantes son funcionales y navegables, no imágenes estáticas. El usuario puede recorrer la plataforma de pantalla en pantalla, rellenar formularios, cambiar entre pestañas, aplicar filtros e interactuar con gráficos _hand-drawn_ con datos simulados, lo que permite evaluar la arquitectura de la información y los flujos de usuario en condiciones próximas al uso real. En segundo lugar, la eficiencia de producción: al reutilizar el mismo entorno de desarrollo de la aplicación principal, se eliminó la fricción de mantener sincronizados dos artefactos distintos —diseño en herramienta externa y código— durante las fases tempranas del proyecto.

El desarrollo del prototipo se aceleró de forma significativa mediante el uso de inteligencia artificial generativa como herramienta de co-desarrollo. Con el apoyo de Claude Code, las más de treinta pantallas que componen el prototipo se construyeron en pocas sesiones de trabajo intensivo, iterando sobre el diseño de cada pantalla con rapidez. Esta modalidad de trabajo, en la que el diseñador y la herramienta de inteligencia artificial colaboran en la generación y refinamiento de código de interfaz, resultó especialmente adecuada para la fase de prototipado, donde la velocidad de iteración tiene más valor que la perfección técnica del código producido.

#figure(
  image("/images/wireframe-home.png", width: 90%),
  caption: [Página de inicio del prototipo interactivo (_wireframe_). Se muestran los indicadores clave del mercado de la vivienda, el buscador por zona, el acceso a las secciones principales y un gráfico de evolución de precios con estilo _hand-drawn_.],
) <fig:wireframe-home>

El prototipo cubre la totalidad de las secciones principales de la plataforma. La página de inicio integra indicadores clave del mercado, un buscador por zona y acceso directo a las secciones principales. La sección de precios y comparativas incluye seis vistas diferenciadas: evolución temporal de precios, ranking de zonas, precio por metro cuadrado, indicadores de asequibilidad, comparativa entre datos oficiales y datos de portales inmobiliarios, y comparación entre múltiples zonas simultáneas. La sección de reportes ciudadanos comprende el listado de reportes con filtros, la vista de detalle de un reporte individual, el formulario de envío en tres pasos progresivos y el mapa de reportes. Se incorpora también una sección de reseñas de agentes inmobiliarios. El área de datos abiertos cuenta con un explorador de datos por municipio, una herramienta de descarga y una página de fuentes y metodología. La zona de usuario incluye el perfil personal con el estado de los reportes enviados, las zonas favoritas y las alertas de precios. Por último, la sección de información recoge la página _Acerca de_, las preguntas frecuentes, el glosario de términos y la guía de derechos del inquilino.

#figure(
  image("/images/wireframe-precios-evolucion.png", width: 90%),
  caption: [Vista de evolución temporal de precios del prototipo interactivo. La pantalla muestra el selector de zona, el gráfico de líneas con estilo _hand-drawn_, los filtros de periodo y tipo de vivienda, y el acceso a las demás vistas de la sección de precios y comparativas.],
) <fig:wireframe-precios-evolucion>

El prototipo se desplegó públicamente y se mantuvo accesible en la URL https://www.danielramos.me/viviendaencrisis/ durante el periodo de validación. Sobre esta versión desplegada se realizó una validación informal con dos usuarios reales, quienes navegaron libremente por la estructura de la plataforma sin recibir orientación previa. En ambos casos, los participantes fueron capaces de identificar correctamente las secciones principales, comprender la organización de los contenidos y completar los recorridos de usuario más habituales —consulta de precios por zona, envío de un reporte ciudadano y descarga de datos— sin necesidad de instrucciones adicionales. Estos resultados validaron las decisiones de arquitectura de la información tomadas en las fases anteriores (@sec:arquitectura-informacion) y confirmaron que la estructura propuesta resultaba comprensible para perfiles de usuario sin formación técnica especializada, en línea con los requisitos identificados en el estudio del público objetivo (@sec:publico-objetivo).
