== Propuesta gráfica de la interfaz <sec:propuesta-grafica>

=== Justificación del lenguaje visual

La elección de un lenguaje visual para una plataforma de datos públicos no es una decisión meramente estética: determina el tipo de relación que el sistema establece con quien lo usa y los valores que comunica antes de que el usuario lea una sola línea de texto. En este proyecto, se optó por el constructivismo ruso de los años veinte del siglo XX como referente visual principal, en lugar de los sistemas de diseño neutros y corporativos predominantes en las plataformas de datos contemporáneas.

El constructivismo ruso fue un movimiento artístico que surgió en la Unión Soviética en torno a 1921 al servicio de la transformación social y la comunicación de masas. Sus principales exponentes —Alexander Rodchenko, El Lissitzky, Liubov Popova y Aleksei Gan, entre otros— desarrollaron un vocabulario visual construido sobre tres principios fundamentales: economía de medios (ningún elemento sin función), composición activa (diagonales, asimetría y tensión visual) y comunicación directa (tipografía en mayúsculas, alto contraste, colores limitados pero intensos). Gan teorizó estos principios en su manifiesto _Constructivismo_ (1922), donde declaraba que el arte debía abandonar la contemplación pasiva y convertirse en un instrumento de intervención en la realidad social.

Esta genealogía resultó especialmente pertinente para _Vivienda en Crisis_. La plataforma no es un portal de consulta neutral: nace de la constatación de una crisis estructural que afecta el derecho a la vivienda de amplios sectores de la población española, tal como se argumentó en la sección de contexto y justificación del trabajo. Un lenguaje visual reivindicativo y de alta carga comunicativa se alinea con esa intención de fondo mejor que una estética minimalista sin posición. El cartel constructivista fue, en su origen, un instrumento de denuncia y movilización; la interfaz se concibió con esa misma lógica: directa, impactante y sin adornos que diluyeran el mensaje.

Desde el punto de vista compositivo, se tomaron como referencias directas las obras más emblemáticas del movimiento: las composiciones diagonales y el uso del fotomontaje de Rodchenko, el espacio negativo y la geometría tensa de _Golpea a los Blancos con la Cuña Roja_ de El Lissitzky, y la abstracción geométrica de las composiciones de Popova. Estos referentes informaron las decisiones de maquetación, la jerarquía tipográfica y el sistema de color de la plataforma, sin convertirse en una reproducción literal del estilo histórico, sino en una reinterpretación funcional aplicada a una interfaz web contemporánea.

=== Sistema de diseño en Figma

Con base en el referente visual descrito, se desarrolló un sistema de diseño completo en Figma que materializa los principios constructivistas en decisiones de diseño concretas y reproducibles. El sistema se estructuró en torno a cuatro capas interdependientes: fundaciones visuales (_foundations_), tokens de diseño, estilos de texto y biblioteca de componentes.

Las fundaciones establecen los principios compositivos que rigen la apariencia global de la plataforma. Se adoptó un sistema de retícula multicolumna con márgenes generosos que favorece la asimetría controlada. Los números grandes —estadísticas clave, porcentajes, indicadores de precio— se trataron como elementos gráficos en sí mismos, con tamaños de tipografía muy superiores a los habituales en este tipo de interfaces, de forma que la cifra comunica antes de que el usuario la lea en contexto. Las líneas diagonales y los bordes en trazos gruesos se emplean como recursos compositivos que aportan tensión visual sin recurrir a ilustraciones o iconografía compleja.

Los tokens de color definieron una paleta deliberadamente limitada de alto contraste, fiel a la economía cromática del constructivismo: rojo intenso (`\#CC0000`) como color de acción, énfasis y alerta; negro (`\#1A1A1A`) como base estructural; crema (`\#F5E6C8`) y blanco roto (`\#FAF7F0`) como fondos cálidos que suavizan el contraste sin perder legibilidad; y gris oscuro (`\#3D3D3D`) para los textos secundarios y los estados desactivados. Esta paleta se implementó como variables de Figma, lo que permite su propagación automática a todos los componentes y facilita el mantenimiento de la consistencia visual a lo largo de todo el sistema.

La jerarquía tipográfica se articuló en cuatro niveles con propósitos diferenciados. Los títulos principales se maquetaron en tipografía condensada en mayúsculas (Oswald o Bebas Neue), en línea directa con los carteles constructivistas, donde la letra gruesa y compacta concentra la atención inmediata. Los subtítulos y encabezados de sección emplean Montserrat, una tipografía geométrica de origen humanista que conserva la rigidez formal sin sacrificar la legibilidad en tamaños medios. El cuerpo de texto utiliza Inter o Source Sans Pro, elegidas por su claridad en pantalla a tamaños pequeños. Los datos numéricos —precios, índices, fechas— se representan en JetBrains Mono, una tipografía monoespaciada que alinea verticalmente los valores en tablas y listados y refuerza la percepción de precisión en los datos.

La biblioteca de componentes se diseñó a partir de los principios anteriores. Las tarjetas de datos presentan un borde izquierdo en rojo grueso que actúa como marcador visual de énfasis, con los números prominentes en la parte superior y la etiqueta descriptiva subordinada. Los botones de acción primaria adoptan esquinas rectas —sin radio de borde— y fondo rojo, coherentes con la estética constructivista y diferenciados con claridad de los botones secundarios en contorno. La barra de navegación global se compone sobre fondo negro con los enlaces en crema, creando un zócalo visual que ancla la interfaz en la parte superior. La iconografía se limita a formas geométricas angulares, prescindiendo de los iconos redondeados habituales en los sistemas de diseño actuales.

Las directrices para las visualizaciones de datos completaron el sistema. Los mapas coropléticos se definen con una escala cromática que va del crema al rojo intenso, donde el rojo señala los valores extremos —los precios más altos o los indicadores de mayor tensión habitacional— y el crema los valores más bajos, con lo que la paleta del sistema se extiende de forma coherente a las visualizaciones. Los gráficos de líneas y barras adoptan un estilo plano (_flat_), sin gradientes ni efectos de profundidad, utilizando el rojo y el negro sobre fondo crema como colores principales de las series de datos.

#figure(
  image("/images/DesignSystem.png", width: 100%),
  caption: [Vista general del sistema de diseño desarrollado en Figma, que muestra las fundaciones compositivas, los tokens de color, la jerarquía tipográfica y la biblioteca de componentes derivados del lenguaje visual constructivista.],
) <fig:design-system>
