== Contexto y justificación del Trabajo <sec:contexto>

=== La vivienda como problema social prioritario

En enero de 2026, el 42,6% de la población española situaba la vivienda como el principal problema del país, según el Barómetro del #cite(<cis_barometro_enero_2026>, form: "prose"). Se trata de un récord absoluto de la serie histórica que supera el anterior máximo registrado en septiembre de 2007, en plena expansión de la burbuja inmobiliaria, y que equivale prácticamente a triplicar los niveles de preocupación medidos apenas tres años antes. La escalada ha sido continua y acelerada: en diciembre de 2024 la vivienda ocupaba ya el primer puesto con un 22,3% @cis_barometro_dic_2024, en noviembre de 2025 alcanzaba el 39,9% @cis_barometro_nov_2025, y a comienzos de 2026 rompía todos los precedentes registrados.

La dimensión europea confirma la excepcionalidad del caso español. Según el Eurobarómetro Estándar 102, correspondiente al otoño de 2024, el 36% de la ciudadanía española identificaba la vivienda como su principal preocupación, frente a una media del 13% en el conjunto de la Unión Europea @eurobarometro_102_2024. España pasó del quinto al primer puesto en el ranking de preocupaciones nacionales en menos de dos años. El 52% de la ciudadanía española consideraba, además, que el presupuesto de la UE debería priorizar la política de vivienda, frente al 26% de media comunitaria @eurobarometro_102_2024. Estos datos revelan que la crisis habitacional española no es solo una percepción subjetiva, sino un fenómeno estadísticamente diferenciado del contexto europeo.

=== Dimensiones de la crisis: precios, acceso y brecha salarial

La intensidad de la preocupación ciudadana responde a una realidad material documentada con precisión. Entre 2015 y 2023, según datos de Eurostat recogidos en el Informe Anual 2024 del #cite(<defensor_pueblo_2024>, form: "prose"), el precio de compra de vivienda en España se incrementó un 42% ---casi el doble que los salarios--- y el de los alquileres un 58%. En términos comparativos, el precio medio de venta alcanzó en enero de 2026 los 2.650 €/m², un máximo histórico que acumula un incremento interanual del 18,4% @idealista_enero_2026. Para el acceso mediante compra, la ratio entre el precio de la vivienda y la renta bruta disponible del hogar alcanzó 7,8 años en el tercer trimestre de 2025, con un esfuerzo teórico anual del 34,9% @banco_espana_indicadores_2025, muy por encima del umbral del 30% que la literatura especializada considera el límite de la accesibilidad razonable.

La situación es especialmente grave en el mercado del alquiler. El estudio conjunto de #cite(<fotocasa_infojobs_2025>, form: "prose") documentó que entre 2021 y 2024 el precio medio del alquiler en España creció un 29,4%, mientras los salarios aumentaron apenas un 7,4% en el mismo período. Esta brecha, que en términos relativos supone que los precios del alquiler crecieron casi cuatro veces más deprisa que las retribuciones salariales, define el núcleo estructural del problema de acceso. La consecuencia directa es un sobreesfuerzo económico generalizado: para el quintil de ingresos más bajo, el esfuerzo mediano de alquiler alcanzaba en 2022 el 43,1% de la renta bruta, según el Documento Ocasional 2432 del #cite(<banco_espana_doc_2432>, form: "prose").

#include "../99_charts/alquiler_vs_salarios.typ"

El impacto sobre los jóvenes reviste una gravedad particular. La tasa de emancipación de la población de entre 16 y 29 años se situaba en el 15,2% en el segundo semestre de 2024, según el Observatorio de Emancipación del #cite(<cje_emancipacion_2024>, form: "prose"). Un joven que accede al mercado laboral en las condiciones salariales medias de su cohorte destinaba en ese período más del 90% de su salario neto al pago de un alquiler medio de mercado, una proporción que hace materialmente inviable la independencia residencial sin apoyo familiar o institucional.

En el extremo más grave del espectro, los datos del #cite(<cgpj_2025>, form: "prose") documentan 27.564 lanzamientos judiciales en 2024, un 3,4% más que el año anterior, de los cuales el 74,6% correspondieron a impago de alquiler. En 2023 se produjeron 26.659 lanzamientos @cgpj_2024. La composición actual de los desahucios es estructuralmente distinta a la de la crisis hipotecaria de 2008-2015: si entonces los lanzamientos hipotecarios eran mayoritarios, hoy son los desahucios por alquiler los que dominan la estadística, lo que refleja el desplazamiento de amplias capas de la población desde la propiedad hacia un mercado de alquiler sometido a una presión creciente.

La respuesta del sector público ha sido insuficiente en términos comparativos. El parque de vivienda social en España representa apenas el 2,5% del total, frente a una media del 10% en la Unión Europea, el 17% en Francia y el Reino Unido, y el 30% en los Países Bajos @defensor_pueblo_2024. El gasto público en política de vivienda se sitúa en torno al 0,1% del PIB, frente al 0,5% de media europea, según datos de #cite(<eurostat_housing_expenditure>, form: "prose"). Más de la mitad de la vivienda protegida construida entre 2005 y 2018 ha sido descalificada y devuelta al mercado privado @defensor_pueblo_2024.

=== El alquiler vacacional como factor de presión sobre el mercado residencial

La expansión de las plataformas de alquiler vacacional a corto plazo ha añadido una presión adicional —y cuantitativamente significativa— sobre un parque residencial ya sometido a tensiones estructurales. Según la estadística experimental del #cite(<ine_vut_experimental>, form: "prose"), el número de viviendas de uso turístico (VUT) en España alcanzó un máximo de aproximadamente 403.000 unidades antes de estabilizarse en torno a las 329.000, lo que representa cerca del 10% del mercado de alquiler según el #cite(<banco_espana_informe_anual_2023>, form: "prose"). La dimensión de la ilegalidad en el sector es especialmente relevante: el Ministerio de Vivienda y Agenda Urbana notificó en febrero de 2026 la existencia de 86.275 VUT ilegales, equivalentes a 435.689 plazas y al 23% de la oferta total del segmento @mivau_vut_ilegales_2026. Esta situación no es homogénea a nivel territorial: en Madrid, el Plan RESIDE constató que únicamente entre 1.131 y 1.200 VUT operaban con licencia sobre un total estimado de entre 16.100 y 17.360, lo que implica que el 92,7% del segmento funcionaba al margen de la normativa @plan_reside_madrid. En Barcelona, la presión fiscalizadora acumulada desde 2016 ha dado lugar a más de 10.500 sanciones y al cierre de 9.700 VUT ilegales @ajuntament_barcelona_vut_2024. La concentración empresarial en el sector añade una dimensión financiera al fenómeno: según el análisis publicado por #cite(<cocola_gant_financialisation_barcelona_2025>, form: "prose"), el 56% de los titulares de licencia de VUT en Barcelona son personas jurídicas, y el 8,8% del total de titulares ---382 propietarios--- acumulan el 51% de las VUT con licencia, lo que revela una lógica de extracción de renta con escasa vinculación a la economía colaborativa que motivó el surgimiento inicial de estas plataformas.

La evidencia empírica sobre el impacto de la proliferación de VUT en los precios residenciales es sólida y metodológicamente rigurosa. El estudio de referencia para el contexto español es el de #cite(<garcia_lopez_airbnb_barcelona_2020>, form: "prose"), que aplica una estrategia de variables instrumentales de tipo shift-share a datos de Barcelona y estima un efecto medio de +1,9% sobre los alquileres y de +4,6% sobre los precios de transacción, con efectos notablemente superiores en los vecindarios con mayor densidad de Airbnb: hasta +7% en alquileres y +17% en precios de venta en el decil con mayor concentración de plataformas. Este patrón de heterogeneidad espacial es consistente con los hallazgos de #cite(<barron_airbnb_prices_2021>, form: "prose") para el mercado estadounidense, donde un incremento del 1% en la oferta de Airbnb se asocia con un aumento del 0,018% en los alquileres y del 0,026% en los precios de venta, siendo Airbnb responsable de aproximadamente una quinta parte del incremento anual de rentas entre 2012 y 2016. En el entorno ibérico más próximo, #cite(<franco_santos_airbnb_portugal_2021>, form: "prose") documentaron para Portugal un aumento medio del 3,7% en los precios de la vivienda por cada punto porcentual de incremento en la cuota de mercado de Airbnb, con efectos de hasta el 32,3% en las parroquias más turísticas de Lisboa y Oporto. El #cite(<banco_espana_informe_anual_2023>, form: "prose") confirma institucionalmente este patrón para España, al señalar que los barrios con mayor concentración de VUT presentan incrementos relativos de precios superiores a la media. Es importante reconocer, no obstante, que la expansión del alquiler vacacional opera junto a otros factores —como el déficit estructural de vivienda nueva, que el #cite(<banco_espana_doc_2432>, form: "prose") cifra en aproximadamente 600.000 unidades acumuladas entre 2022 y 2025— que explican de manera complementaria la trayectoria alcista de los precios @fedea_vut_2026.

Las consecuencias sociales de la turistificación de la vivienda se manifiestan con particular intensidad en los centros históricos de las ciudades de mayor afluencia turística. #cite(<vives_miro_desposesion_palma_2017>, form: "prose") acuñaron el concepto de «desposesión de vivienda por turistización» a partir del análisis del Centro Histórico de Palma de Mallorca, donde documentaron la correlación entre la expansión del alquiler vacacional, la revalorización de los inmuebles y el desplazamiento forzado de la población residente. En Madrid, el trabajo de #cite(<mazorra_lavapies_2023>, form: "prose") constató que las VUT representaban más del 12% del parque total de viviendas en el barrio de Lavapiés y aproximadamente el 25% del stock de alquiler en el Distrito Centro, documentando un proceso de sustitución demográfica en el que la población de menor renta es progresivamente reemplazada por residentes de mayor poder adquisitivo. Para el análisis conceptual del desplazamiento, el marco propuesto por #cite(<cocola_gant_displacement_2018>, form: "prose") distingue cuatro modalidades —directo, por exclusión, por deterioro del entorno y colectivo— que permiten capturar la complejidad de un fenómeno que trasciende el simple desahucio individual. La intensidad de esta problemática ha generado respuestas sociales de alcance inédito: en las Islas Canarias, la movilización ciudadana del 20 de abril de 2024 convocó entre 57.000 y 200.000 personas en las calles, configurando la mayor protesta de la historia del archipiélago, y motivó la aprobación de la Ley 6/2025 canaria como respuesta legislativa @ley_6_2025_canarias. Estos procesos de desplazamiento no se producen de forma aislada, sino que se inscriben en la dinámica más amplia de financiarización del parque residencial descrita en las secciones precedentes.

La gestión efectiva de este fenómeno tropieza, además, con un obstáculo informativo de primer orden. El Reglamento (UE) 2024/1028, aprobado en abril de 2024, identifica la «falta de información fiable» como el principal impedimento para la regulación eficaz del alquiler vacacional en el conjunto de la Unión Europea y obliga a las plataformas digitales a compartir datos de actividad con las autoridades competentes @reglamento_ue_2024_1028. En el plano analítico, #cite(<fedea_vut_2026>, form: "prose") subraya la necesidad de «información detallada y mecanismos de supervisión efectivos» para evaluar el impacto real del sector y diseñar intervenciones regulatorias proporcionadas. La ausencia de un registro centralizado, la proliferación de estructuras societarias que dificultan la identificación de los operadores reales y la dispersión de los datos entre registros autonómicos y municipales incompatibles constituyen, en conjunto, una opacidad informativa que agrava la asimetría ya existente en el mercado residencial. Esta capa adicional de opacidad, específica del segmento vacacional, refuerza el diagnóstico general sobre la fragmentación de los datos de vivienda en España que se desarrolla en la sección siguiente.

=== Datos fragmentados, poder concentrado

Ante esta situación, la información disponible sobre el mercado de la vivienda en España no carece de volumen, sino de accesibilidad, integración y sistematicidad. Los datos existen, pero se encuentran dispersos entre fuentes heterogéneas con periodicidades, metodologías y granularidades incompatibles: el Ministerio de Vivienda y Agenda Urbana (MIVAU/SERPAVI) publica índices trimestrales de precios; el Instituto Nacional de Estadística (INE) proporciona datos censales y de transacciones; el Catastro ofrece información de uso y superficie; y portales privados como Idealista o Fotocasa publican índices de precios de oferta con granularidad a nivel de sección censal.

#figure(
  block(
    width: 100%,
    inset: 1em,
    table(
      columns: (1.2fr, 1fr, 1fr, 1fr, 1fr),
      align: (left, center, center, center, center),
      stroke: 0.5pt + luma(180),
      fill: (x, y) => if y == 0 { rgb("#2c3e50").lighten(80%) } else if calc.odd(y) { luma(245) } else { white },
      table.header(
        [*Fuente*], [*Cobertura*], [*Periodicidad*], [*Granularidad*], [*Acceso*],
      ),
      [MIVAU/SERPAVI], [Nacional], [Trimestral], [Provincial / municipal], [Público abierto],
      [INE (censo, transacciones)], [Nacional], [Anual / trimestral], [Municipal / sección censal], [Público abierto],
      [Catastro], [Nacional], [Continua], [Parcela], [Público parcial#super[1]],
      [Idealista], [Zonas urbanas], [Mensual], [Sección censal], [API de pago],
      [Fotocasa], [Zonas urbanas], [Mensual], [Distrito / barrio], [Restringido],
    ),
  ),
  caption: [Comparativa de las principales fuentes de datos de vivienda en España: cobertura geográfica, periodicidad de actualización, granularidad espacial y nivel de accesibilidad. #super[1]El Catastro permite consultas individuales pero limita la descarga masiva.],
) <fig:fragmentacion-fuentes>

Esta fragmentación no afecta a todos los actores por igual. Los agentes con mayor capacidad de procesamiento y mayor acceso a datos —fondos de inversión, SOCIMIs, plataformas inmobiliarias— disponen de una ventaja estructural sobre la ciudadanía y las administraciones locales. El informe del #cite(<idra_2024>, form: "prose") señalaba que "Es vital superar la enorme opacidad y asimetría de información que caracteriza al mercado del alquiler". La investigación de #cite(<civio_megatenedores_2024>, form: "prose") identificó a 737 megatenedores que controlan más de 178.000 viviendas alquiladas, aproximadamente el 10% de los alquileres formalizados en España, con una concentración que la ciudadanía y los municipios no pueden rastrear fácilmente mediante fuentes públicas.

La asimetría de información en los mercados de vivienda es un fenómeno documentado académicamente. #cite(<ambrose_diop_2021>, form: "prose") demostraron que los propietarios trasladan los costes regulatorios al precio del alquiler e invierten en mecanismos de selección de inquilinos que restringen el acceso a la vivienda de los hogares con menor renta. #cite(<st_hilaire_2023>, form: "prose") complementaron esta perspectiva al mostrar que, mientras los propietarios realizan comprobaciones crediticias y recurren a listas negras de inquilinos que han comparecido ante tribunales de vivienda, estos últimos carecen de capacidad equivalente para verificar si el arrendador ha respetado las directrices de precios o para identificar patrones de mal comportamiento ocultos tras sociedades anónimas, lo que amplía la brecha informativa entre ambas partes. Esta asimetría bidireccional no es un fallo de mercado residual, sino un elemento constitutivo de la relación entre propietario e inquilino en mercados no regulados.

Los datos más granulares y actualizados, a nivel de sección censal, están controlados en la práctica por los portales privados, cuyas estadísticas reflejan precios de oferta y no de transacción efectiva, con el sesgo al alza que ello introduce @banco_espana_doc_2432. No existe en España ninguna plataforma pública que contraste sistemáticamente la evolución de los precios de la vivienda con la evolución salarial a nivel territorial desagregado. La consecuencia es que la ciudadanía, las organizaciones sociales y los representantes locales toman decisiones sobre una materia que afecta al derecho fundamental a la vivienda con una información incompleta, fragmentada y, en parte, mediada por actores con intereses en el mercado.

=== El vacío de herramientas públicas y la necesidad de un observatorio ciudadano

España cuenta con iniciativas valiosas en el ámbito del seguimiento del mercado de la vivienda, pero ninguna de ellas cubre de manera integral las necesidades de la ciudadanía. El Observatorio de Vivienda y Suelo del MIVAU publica más de 600 indicadores en boletines trimestrales y anuales, pero lo hace en formatos estáticos —PDF y hojas de cálculo— sin interactividad ni integración con otras fuentes. Provivienda mantiene un observatorio de indicadores contextualizados centrado en los desahucios. El medio de periodismo de datos Datadista produce mapas interactivos con granularidad a nivel de sección censal, pero se trata de una iniciativa periodística sin mecanismos de participación ciudadana. El Observatori DESCA desarrolla investigación rigurosa desde la perspectiva de los derechos humanos, pero sin herramienta pública de datos abiertos. Estas iniciativas, cuyo análisis se desarrolla en el @cap:materiales, presentan limitaciones complementarias que justifican la necesidad de una nueva aproximación.

El marco conceptual de la tecnología cívica (civic tech) y los datos abiertos ofrece la base teórica para esta aproximación. #cite(<navalkha_2021>, form: "prose") documentó cómo activistas en Boston y Nueva York utilizaron datos gubernamentales abiertos para avanzar en la justicia habitacional, identificando en el acceso a la información un instrumento que potencia la capacidad de incidencia política y la organización comunitaria frente a los procesos de desplazamiento. #cite(<maharawal_mcelroy_2018>, form: "prose") describieron el Anti-Eviction Mapping Project como un modelo de contracartografía que combina la visualización de datos de desahucios con la historia oral comunitaria, convirtiendo los datos en un instrumento de narrativa colectiva. La experiencia comparada muestra que la democratización del acceso a datos de vivienda no es un fin en sí mismo, sino una condición necesaria para la rendición de cuentas y la participación informada en las decisiones que afectan al hábitat.

=== Motivación y enfoque del proyecto

La vivienda constituye un derecho reconocido en el artículo 47 de la Constitución Española, que obliga a los poderes públicos a promover las condiciones necesarias y a establecer las normas pertinentes para hacer efectivo el acceso a una vivienda digna y adecuada. Ya en 2006, el Relator Especial de Naciones Unidas sobre vivienda adecuada identificó, tras su visita a España, deficiencias estructurales como la especulación generalizada, la insuficiencia de vivienda pública de alquiler y el tratamiento de la vivienda como mera mercancía @kothari_spain_2008. La Ley 12/2023, de 24 de mayo, por el derecho a la vivienda, se propuso corregir estas carencias con mecanismos como la declaración de zonas de mercado residencial tensionado y la regulación de grandes tenedores @ley_vivienda_2023. No obstante, como evidencian los indicadores expuestos en las secciones precedentes, los problemas estructurales persisten y el propio Defensor del Pueblo insta a las administraciones a utilizar las herramientas que contiene la Ley 12/2023, cuyo potencial permanece en buena medida sin desplegar @defensor_pueblo_2024.

Este trabajo de fin de máster nace de la convergencia entre la relevancia social del problema descrito y la oportunidad técnica que ofrecen los datos abiertos, las tecnologías de visualización y los marcos de participación ciudadana digital. El mercado de la vivienda en España padece una opacidad informativa que beneficia estructuralmente a quienes poseen más información, en detrimento de quienes más necesitan acceder a ella. La financiarización creciente del sector @aalbers_2016 ha generado una relación asimétrica entre propietarios institucionales y arrendatarios individuales que se retroalimenta, en parte, de esta disparidad informativa.

"Vivienda en Crisis" se ha desarrollado como un observatorio público de vivienda accesible en línea, construido con tecnologías web abiertas y basado en datos de fuentes públicas oficiales. La plataforma integra visualizaciones de la evolución temporal de precios de alquiler y compraventa, comparativas entre zonas geográficas, contraste con indicadores salariales y mapas coropléticos a escala de comunidad autónoma y municipio. Incorpora, asimismo, un sistema de reportes ciudadanos que permite a la población residente documentar y comunicar situaciones de abuso o irregularidad en el mercado de la vivienda. El enfoque técnico —cuyo detalle corresponde a los capítulos siguientes— combina un desarrollo web de arquitectura moderna con una canalización de datos abiertos reproducible y auditable.

La pertinencia académica del proyecto reside en su naturaleza como aplicación web completa desarrollada de extremo a extremo: desde la arquitectura del sistema y la implementación de la API hasta la construcción de la interfaz de usuario, pasando por la integración de fuentes de datos heterogéneas y el despliegue en producción. El Máster Universitario en Desarrollo de Sitios y Aplicaciones Web proporciona el marco formativo necesario para abordar cada una de estas capas —incluido el diseño de interfaces y la experiencia de usuario, tratados en su propia asignatura—, y el presente trabajo las articula en torno a un problema real cuya complejidad informativa exige soluciones técnicas rigurosas. La dimensión social del problema —el acceso a la vivienda como ejercicio del derecho constitucional— dota al proyecto de una relevancia que trasciende lo puramente técnico y lo sitúa en el campo de la tecnología cívica como instrumento de transparencia y rendición de cuentas.
