== Contexto y justificación del Trabajo

=== La vivienda como problema social prioritario

En enero de 2026, el 42,6% de la población española situaba la vivienda como el principal problema del país, según el Barómetro del Centro de Investigaciones Sociológicas @cis_barometro_enero_2026. Se trata de un récord absoluto de la serie histórica que supera el anterior máximo registrado en septiembre de 2007, en plena expansión de la burbuja inmobiliaria, y que equivale prácticamente a triplicar los niveles de preocupación medidos apenas tres años antes. La escalada ha sido continua y acelerada: en diciembre de 2024 la vivienda ocupaba ya el primer puesto con un 22,3% @cis_barometro_dic_2024, en noviembre de 2025 alcanzaba el 39,9% @cis_barometro_nov_2025, y a comienzos de 2026 rompía todos los precedentes registrados.

La dimensión europea confirma la excepcionalidad del caso español. Según el Eurobarómetro Estándar 102, correspondiente al otoño de 2024, el 36% de la ciudadanía española identificaba la vivienda como su principal preocupación, frente a una media del 13% en el conjunto de la Unión Europea @eurobarometro_102_2024. España pasó del quinto al primer puesto en el ranking de preocupaciones nacionales en menos de dos años. El 52% de la ciudadanía española consideraba, además, que el presupuesto de la UE debería priorizar la política de vivienda, frente al 26% de media comunitaria @eurobarometro_102_2024. Estos datos revelan que la crisis habitacional española no es solo una percepción subjetiva, sino un fenómeno estadísticamente diferenciado del contexto europeo.

=== Dimensiones de la crisis: precios, acceso y brecha salarial

La intensidad de la preocupación ciudadana responde a una realidad material documentada con precisión. Entre 2015 y 2023, según datos de Eurostat recogidos en el Informe Anual 2024 del Defensor del Pueblo, el precio de compra de vivienda en España se incrementó un 42% ---casi el doble que los salarios--- y el de los alquileres un 58% @defensor_pueblo_2024. En términos comparativos, el precio medio de venta alcanzó en enero de 2026 los 2.650 €/m², un máximo histórico que acumula un incremento interanual del 18,4% @idealista_enero_2026. Para el acceso mediante compra, la ratio entre el precio de la vivienda y la renta bruta disponible del hogar alcanzó 7,8 años en el tercer trimestre de 2025, con un esfuerzo teórico anual del 34,9% @banco_espana_indicadores_2025, muy por encima del umbral del 30% que la literatura especializada considera el límite de la accesibilidad razonable.

La situación es especialmente grave en el mercado del alquiler. El estudio conjunto de Fotocasa e InfoJobs publicado en 2025 documentó que entre 2021 y 2024 el precio medio del alquiler en España creció un 29,4%, mientras los salarios aumentaron apenas un 7,4% en el mismo período @fotocasa_infojobs_2025. Esta brecha, que en términos relativos supone que los precios del alquiler crecieron casi cuatro veces más deprisa que las retribuciones salariales, define el núcleo estructural del problema de acceso. La consecuencia directa es un sobreesfuerzo económico generalizado: para el quintil de ingresos más bajo, el esfuerzo mediano de alquiler alcanzaba en 2022 el 43,1% de la renta bruta, según el Documento Ocasional 2432 del Banco de España @banco_espana_doc_2432.

#include "../99_charts/alquiler_vs_salarios.typ"

El impacto sobre los jóvenes reviste una gravedad particular. La tasa de emancipación de la población de entre 16 y 29 años se situaba en el 15,2% en el segundo semestre de 2024, según el Observatorio de Emancipación del Consejo de la Juventud de España @cje_emancipacion_2024. Un joven que accede al mercado laboral en las condiciones salariales medias de su cohorte destinaba en ese período más del 90% de su salario neto al pago de un alquiler medio de mercado, una proporción que hace materialmente inviable la independencia residencial sin apoyo familiar o institucional.

En el extremo más grave del espectro, los datos del Consejo General del Poder Judicial documentan 27.564 lanzamientos judiciales en 2024, un 3,4% más que el año anterior, de los cuales el 74,6% correspondieron a impago de alquiler @cgpj_2025. En 2023 se produjeron 26.659 lanzamientos @cgpj_2024. La composición actual de los desahucios es estructuralmente distinta a la de la crisis hipotecaria de 2008-2015: si entonces los lanzamientos hipotecarios eran mayoritarios, hoy son los desahucios por alquiler los que dominan la estadística, lo que refleja el desplazamiento de amplias capas de la población desde la propiedad hacia un mercado de alquiler sometido a una presión creciente.

La respuesta del sector público ha sido insuficiente en términos comparativos. El parque de vivienda social en España representa apenas el 2,5% del total, frente a una media del 10% en la Unión Europea, el 17% en Francia y el Reino Unido, y el 30% en los Países Bajos @defensor_pueblo_2024. El gasto público en política de vivienda se sitúa en el 0,06% del PIB, frente al 0,5% de media europea, según datos del Housing Europe Observatory @housing_europe_2023. Más de la mitad de la vivienda protegida construida entre 2005 y 2018 ha sido descalificada y devuelta al mercado privado @defensor_pueblo_2024.

=== Datos fragmentados, poder concentrado

Ante esta situación, la información disponible sobre el mercado de la vivienda en España no carece de volumen, sino de accesibilidad, integración y sistematicidad. Los datos existen, pero se encuentran dispersos entre fuentes heterogéneas con periodicidades, metodologías y granularidades incompatibles: el Ministerio de Vivienda y Agenda Urbana (MIVAU/SERPAVI) publica índices trimestrales de precios; el Instituto Nacional de Estadística (INE) proporciona datos censales y de transacciones; el Catastro ofrece información de uso y superficie; y portales privados como Idealista o Fotocasa publican índices de precios de oferta con granularidad a nivel de sección censal.

#figure(
  block(
    width: 100%,
    inset: 1em,
    table(
      columns: (1.2fr, 1fr, 1fr, 1fr, 1fr),
      align: (left, center, center, center, center),
      stroke: 0.5pt + luma(180),
      fill: (x, y) => if y == 0 { rgb("#2c3e50").lighten(80%) } else if calc.odd(y) { luma(245) } else { white },
      table.header(
        [*Fuente*], [*Cobertura*], [*Periodicidad*], [*Granularidad*], [*Acceso*],
      ),
      [MIVAU/SERPAVI], [Nacional], [Trimestral], [Provincial / municipal], [Público abierto],
      [INE (censo, transacciones)], [Nacional], [Anual / trimestral], [Municipal / sección censal], [Público abierto],
      [Catastro], [Nacional], [Continua], [Parcela], [Público parcial#super[1]],
      [Idealista], [Zonas urbanas], [Mensual], [Sección censal], [API de pago],
      [Fotocasa], [Zonas urbanas], [Mensual], [Distrito / barrio], [Restringido],
    ),
  ),
  caption: [Comparativa de las principales fuentes de datos de vivienda en España: cobertura geográfica, periodicidad de actualización, granularidad espacial y nivel de accesibilidad. #super[1]El Catastro permite consultas individuales pero limita la descarga masiva.],
) <fig:fragmentacion-fuentes>

Esta fragmentación no afecta a todos los actores por igual. Los agentes con mayor capacidad de procesamiento y mayor acceso a datos —fondos de inversión, SOCIMIs, plataformas inmobiliarias— disponen de una ventaja estructural sobre la ciudadanía y las administraciones locales. El informe del Institut de Drets i Recerca per a l'Acció (IDRA) de 2024 señalaba que "Es vital superar la enorme opacidad y asimetría de información que caracteriza al mercado del alquiler" @idra_2024. La investigación de Civio identificó en 2024 a 737 megatenedores que controlan más de 178.000 viviendas alquiladas, aproximadamente el 10% de los alquileres formalizados en España, con una concentración que la ciudadanía y los municipios no pueden rastrear fácilmente mediante fuentes públicas @civio_megatenedores_2024.

La asimetría de información en los mercados de vivienda es un fenómeno documentado académicamente. Ambrose y Diop (2021) demostraron que los propietarios invierten en mecanismos de selección de inquilinos y trasladan los costes regulatorios al precio, procesos que refuerzan la asimetría en detrimento de quienes alquilan @ambrose_diop_2021. St-Hilaire, Brunila y Wachsmuth (2023) pusieron de manifiesto que mientras los propietarios realizan comprobaciones crediticias y de historial sobre los inquilinos, estos últimos no tienen acceso a información equivalente sobre las condiciones de la propiedad ni sobre el comportamiento del arrendador @st_hilaire_2023. Esta asimetría bidireccional no es un fallo de mercado residual, sino un elemento constitutivo de la relación entre propietario e inquilino en mercados no regulados.

Los datos más granulares y actualizados, a nivel de sección censal, están controlados en la práctica por los portales privados, cuyas estadísticas reflejan precios de oferta y no de transacción efectiva, con el sesgo al alza que ello introduce @banco_espana_doc_2432. No existe en España ninguna plataforma pública que contraste sistemáticamente la evolución de los precios de la vivienda con la evolución salarial a nivel territorial desagregado. La consecuencia es que la ciudadanía, las organizaciones sociales y los representantes locales toman decisiones sobre una materia que afecta al derecho fundamental a la vivienda con una información incompleta, fragmentada y, en parte, mediada por actores con intereses en el mercado.

=== El vacío de herramientas públicas y la necesidad de un observatorio ciudadano

España cuenta con iniciativas valiosas en el ámbito del seguimiento del mercado de la vivienda, pero ninguna de ellas cubre de manera integral las necesidades de la ciudadanía. El Observatorio de Vivienda y Suelo del MIVAU publica más de 600 indicadores en boletines trimestrales y anuales, pero lo hace en formatos estáticos —PDF y hojas de cálculo— sin interactividad ni integración con otras fuentes. Provivienda mantiene un observatorio de indicadores contextualizados centrado en los desahucios. El medio de periodismo de datos Datadista produce mapas interactivos con granularidad a nivel de sección censal, pero se trata de una iniciativa periodística sin mecanismos de participación ciudadana. El Observatori DESCA desarrolla investigación rigurosa desde la perspectiva de los derechos humanos, pero sin herramienta pública de datos abiertos. Estas iniciativas, cuyo análisis se desarrolla en el capítulo 2, presentan limitaciones complementarias que justifican la necesidad de una nueva aproximación.

El marco conceptual de la tecnología cívica (civic tech) y los datos abiertos ofrece la base teórica para esta aproximación. Navalkha (2021) documentó cómo activistas en Boston y Nueva York utilizaron datos gubernamentales abiertos para avanzar en la justicia habitacional, identificando en el acceso a la información un vector de empoderamiento ciudadano tan relevante como las herramientas legislativas @navalkha_2021. Maharawal y McElroy (2018) describieron el Anti-Eviction Mapping Project como un modelo de contracartografía que combina la visualización de datos de desahucios con la historia oral comunitaria, convirtiendo los datos en un instrumento de narrativa colectiva @maharawal_mcelroy_2018. La experiencia comparada muestra que la democratización del acceso a datos de vivienda no es un fin en sí mismo, sino una condición necesaria para la rendición de cuentas y la participación informada en las decisiones que afectan al hábitat.

=== Motivación y enfoque del proyecto

La vivienda constituye un derecho reconocido en el artículo 47 de la Constitución Española, que obliga a los poderes públicos a promover las condiciones necesarias y a establecer las normas pertinentes para hacer efectivo el acceso a una vivienda digna y adecuada. La Ley 12/2023, de 24 de mayo, por el derecho a la vivienda, desarrolló este mandato constitucional con mecanismos como la declaración de zonas de mercado residencial tensionado y la regulación de grandes tenedores @ley_vivienda_2023. No obstante, el Comité Europeo de Derechos Sociales ha admitido quejas colectivas contra España por incumplimiento de la Carta Social Europea en materia de vivienda @consejo_europa_2024, y los relatores especiales de Naciones Unidas han identificado reiteradamente deficiencias estructurales en la garantía del derecho a la vivienda en el país @rajagopal_2021.

Este trabajo de fin de máster nace de la convergencia entre la relevancia social del problema descrito y la oportunidad técnica que ofrecen los datos abiertos, las tecnologías de visualización y los marcos de participación ciudadana digital. El mercado de la vivienda en España padece una opacidad informativa que beneficia estructuralmente a quienes poseen más información, en detrimento de quienes más necesitan acceder a ella. La financiarización creciente del sector @aalbers_2016 ha generado una relación asimétrica entre propietarios institucionales y arrendatarios individuales que se retroalimenta, en parte, de esta disparidad informativa.

"Vivienda en Crisis" se propone como un observatorio público de vivienda accesible en línea, desarrollado con tecnologías web abiertas y basado en datos de fuentes públicas oficiales. La plataforma integrará visualizaciones de la evolución temporal de precios de alquiler y compraventa, comparativas entre zonas geográficas, contraste con indicadores salariales y mapas coropléticos a escala de comunidad autónoma y municipio. Incorporará, asimismo, un sistema de reportes ciudadanos que permitirá a la población residente documentar y comunicar situaciones de abuso o irregularidad en el mercado de la vivienda. El enfoque técnico —cuyo detalle corresponde a los capítulos siguientes— combina un desarrollo web de arquitectura moderna con una canalización de datos abiertos reproducible y auditable.

La pertinencia académica del proyecto reside en la intersección de tres ámbitos del Máster Universitario en Desarrollo de Sitios y Aplicaciones Web: la ingeniería del software orientada a la web, la gestión e integración de datos abiertos, y el diseño de interfaces centrado en la experiencia del usuario para contextos de información compleja. La dimensión social del problema —el acceso a la vivienda como ejercicio del derecho constitucional— dota al proyecto de una relevancia que trasciende lo puramente técnico y lo sitúa en el campo de la tecnología cívica como instrumento de transparencia y rendición de cuentas.
